# Generated by Django 3.2 on 2021-07-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('depoimento', models.TextField()),
                ('data_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_principal', models.ImageField(upload_to='fotoPrincipal')),
                ('data_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotosAcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_acoes', models.ImageField(upload_to='fotosAcoes')),
                ('frase_acoes', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TimeVoluntarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('frase_engracada', models.TextField(max_length=500)),
                ('foto_perfil', models.ImageField(upload_to='voluntarios')),
            ],
        ),
    ]
