# Generated by Django 3.2 on 2021-07-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210724_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoprincipal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
