# Generated by Django 3.2 on 2021-07-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fotoprincipal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosacoes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
