# Generated by Django 3.2 on 2021-07-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210725_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotosacoes',
            old_name='foto_acoes',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='fotosacoes',
            old_name='frase_acoes',
            new_name='frase',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='nome_assinante',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='timevoluntarios',
            old_name='foto_perfil',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='timevoluntarios',
            old_name='frase_engracada',
            new_name='frase',
        ),
    ]
