# Generated by Django 3.2 on 2021-07-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210725_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocaisTrabalhados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.TextField(max_length=100)),
                ('endereco', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NossosDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voluntarios', models.IntegerField()),
                ('visitas_mes', models.IntegerField()),
                ('pessoas_impactadas', models.IntegerField()),
                ('horas_doadas', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='depoimentos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotoDepoimentos'),
        ),
    ]
